### ISSUE TITLE
https://get-release.xyz/ appears down

### ISSUE THREAD

**Issue by AeroNotix** [christophwitzko/github-release-download#4]
As title. 

Unable to make successful requests to https://get-release.xyz/

Looking over recent commits, appears that some changes went in to rename the repository and also change how/where the project is deployed. Hate to say it's related, but it seems related.

**Comment by christophwitzko** [comment]
Hi, I am so sorry for the downtime!
I switched to Google Cloud Run, and there were some issues/delays with setting up SSL certificates. My apologies 🙏 
It is now up and running again 🟢
