### ISSUE TITLE
Requests returning "server error"

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [christophwitzko/github-release-download#5]
For example, https://get-release.xyz/kubernetes/minikube/linux/amd64

**Comment by christophwitzko** [comment]
Sorry about that. I can reproduce the error and I am investigating.

**Comment by christophwitzko** [comment]
@mgabeler-lee-6rs It is working again. 🙏

**Comment by mgabeler-lee-6rs** [comment]
Thank you :grinning:
